// src/react-froala-sample/src/App.js
import { useState, useEffect } from 'react'
import RealTimeFroalaEditor from './components/RealTimeFroalaEditor'
import './App.css';

function App() {

  const { Codox } = window;

  const apiKey = '58e429b0-be4a-4cd8-8c8d-9a37fb0adec0';
  const username = 'Chris';
  const docs = [
    { "id": "doc1", "content": "Hello World" },
    { "id": "doc2", "content": "One two three" }
  ];
  const [activeDoc, setActiveDoc] = useState({ id: null, content: null })
  const [codox, setCodoxInstance] = useState(null)

  useEffect(() => {
    const codoxInstance = new Codox()
    setCodoxInstance(codoxInstance)
  }, [])

  const changeActiveDoc = (doc) => {

    if (doc.id !== activeDoc.id) {

      //leave the session
      codox && codox.stop();

      //create a new codox instance
      const codoxInstance = new Codox()
      setCodoxInstance(codoxInstance)
      setActiveDoc(doc)
    }

  }

  const updateContent = (docId, content) => {
    const index = docs.findIndex((v) => v.id === docId);
    docs[index] = { id: docId, content }
  }


  return (
    <div className="App">
      <div id="app">
        <div className="header">
          <a href="https://www.codox.io" target="_blank">
            <img id="logo" src="https://www.codox.io/assets/img/wave.svg" alt="" />
          </a>
          <div>Create your own Google Docs with Wave + Froala on React</div>
        </div>

        <div className="main-container">
          <div className="document-container">
            <ul className="document-list">
              {docs.map(d =>
                <li key={d.id} onClick={() => changeActiveDoc(d)}>
                  <a className={`document-link ${activeDoc.id === d.id && 'active'}`}>{d.id}</a>
                </li>
              )}

            </ul>
          </div>
          <div id="editor" className="editors">
            {activeDoc.id ? <RealTimeFroalaEditor
              username={username}
              apiKey={apiKey}
              codox={codox}
              docId={activeDoc.id}
              model={activeDoc.content}
              updateContent={updateContent}
            /> : null}

          </div>
        </div>
      </div>

    </div>
  );
}

export default App;

// froala-angular-codox/src/app/app.component.ts
import { Component } from '@angular/core';

declare const Codox: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  docId: any;
  docs = [
    { "id": "doc1", "content": "Hello World" },
    { "id": "doc2", "content": "One two three" },
  ];
  apiKey = "58e429b0-be4a-4cd8-8c8d-9a37fb0adec0";
  username = "Chris";
  currentDoc: any;
  codox: any;


  constructor() {
    this.docId = this.guid();
    this.currentDoc = this.docs[0]
  }

  guid() {
    const s4 = () => {
      return Math.floor((1 + Math.random()) * 0x10000)
        .toString(16)
        .substring(1);
    };
    return (
      s4() + s4() + s4() + s4() + s4() + s4() + s4() + s4()
    );
  }

  onDocClick({ id, content }) {
    if (id !== this.currentDoc.id) {
      if (this.codox) {
        this.codox.stop();
      }
      this.codox = new Codox();
      this.currentDoc = {
        id,
        content,
      };
    }
  }
}

<div class="header">
  <a href="https://www.codox.io" class="logo-link" target="_blank">
    <img id="logo" src="https://www.codox.io/assets/img/wave.svg" alt="">
  </a>
  <div class="logo-title">
    Create your own Google Docs with Wave + Froala on Angular
  </div>
</div>



<div class="main-container">
  <div class="document-container">
    <ul class="document-list">
      <li *ngFor="let doc of docs" [ngClass]="{'active': doc.id === currentDoc.id}" class="document-link"
        (click)="onDocClick(doc)">
        <a>{{ doc.id }}</a>
      </li>
    </ul>
  </div>
  <div class="editors">
    <app-realtime-froala *ngIf="currentDoc.id" class="editor" [apiKey]="apiKey" [username]="username"
      [docId]="currentDoc.id" [codox]="codox" [model]="currentDoc.content">
    </app-realtime-froala>
  </div>
</div>
