// quill-angular-codox/src/app/app.component.ts
import { Component } from '@angular/core';
import Codox from '@codoxhq/quill-provider';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  docs = [
    {
      id: 'd9c6d75e-8ce7-4cd2-9c78-a732a6b7256e',
      name: 'doc1',
      content: 'Hello World',
    },
    {
      id: '8cc0a067-f045-4998-a7b1-782652e01fa7',
      name: 'doc2',
      content: 'One two three',
    },
  ];
  apiKey = '58e429b0-be4a-4cd8-8c8d-9a37fb0adec0';
  username = 'Chris';
  currentDoc: any;
  codox: any;
  boundCallback: Function;

  public ngOnInit() {
    this.boundCallback = this.updateContent.bind(this);
  }

  constructor() {
    this.currentDoc = this.docs[0];
    this.codox = new Codox();
  }

  onDocClick({ id, content }) {
    if (id !== this.currentDoc.id) {
      if (this.codox) {
        this.codox.stop();
      }
      this.codox = new Codox();
      this.currentDoc = {
        id,
        content,
      };
    }
  }

  updateContent(docId, content) {
    this.docs = this.docs.map((d) => {
      if (d.id === docId) {
        return { ...d, content };
      }
      return d;
    });
  }
}

<div class="header">
  <a href="https://www.codox.io" class="logo-link" target="_blank">
    <img id="logo" src="https://www.codox.io/assets/img/wave.svg" alt="">
  </a>
  <div class="logo-title">
    Create your own Google Docs with Wave + Quill on Angular
  </div>
</div>



<div class="main-container">
  <div class="document-container">
    <ul class="document-list">
      <li *ngFor="let doc of docs" [ngClass]="{'active': doc.id === currentDoc.id}" class="document-link"
        (click)="onDocClick(doc)">
        <a>{{ doc.name }}</a>
      </li>
    </ul>
  </div>
  <div class="editors">
    <app-realtime-quill *ngIf="currentDoc.id" class="editor" [apiKey]="apiKey" [username]="username"
      [docId]="currentDoc.id" [codox]="codox" [model]="currentDoc.content" [boundCallback]="boundCallback">
    </app-realtime-quill>
  </div>
</div>

// react-quill-codox/src/App.js
import { useState, useEffect } from 'react';
import RealTimeQuillEditor from './components/RealTimeQuillEditor';
import './App.css';
import Codox from '@codoxhq/quill-provider';

function App() {
  const apiKey = '58e429b0-be4a-4cd8-8c8d-9a37fb0adec0';
  const username = 'Chris';
  const [docs, updateDocs] = useState([
    { id: '9d52d64b-f7c5-40de-8137-629376ffbc76', name: 'doc1', content: 'Hello World' },
    { id: '9d52d64b-f7c5-40de-8137-629376ffbc77', name: 'doc2', content: 'One two three' },
  ]);
  const [activeDoc, setActiveDoc] = useState(docs[0]);
  const [codox, setCodoxInstance] = useState(null);

  useEffect(() => {
    const codoxInstance = new Codox();
    setCodoxInstance(codoxInstance);
  }, []);

  const changeActiveDoc = (doc) => {
    if (doc.id !== activeDoc.id) {
      //leave the session
      codox && codox.stop();

      //create a new codox instance
      const codoxInstance = new Codox();
      setCodoxInstance(codoxInstance);
      setActiveDoc(doc);
    }
  };

  const updateContent = (docId, content) => {
    const updatedDoc = docs.map((doc) => {
      if (doc.id === docId) {
        return { ...doc, content };
      }
      return doc;
    });
    updateDocs(updatedDoc);
  };

  return (
    <div className="App">
      <div id="app">
        <div className="header">
          <a className="logo-link" href="https://www.codox.io" target="_blank">
            <img id="logo" src="https://www.codox.io/assets/img/wave.svg" alt="" />
          </a>
          <div className="logo-title">Create your own Google Docs with Wave + Quill on React</div>
        </div>

        <div className="main-container">
          <div className="document-container">
            <ul className="document-list">
              {docs.map((d) => (
                <li key={d.id} onClick={() => changeActiveDoc(d)}>
                  <a className={`document-link ${activeDoc.id === d.id && 'active'}`}>{d.name}</a>
                </li>
              ))}
            </ul>
          </div>
          <div className="editors">
            {activeDoc.id ? (
              <RealTimeQuillEditor
                username={username}
                apiKey={apiKey}
                codox={codox}
                docId={activeDoc.id}
                model={activeDoc.content}
                updateContent={updateContent}
              />
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
