// src/vue-froala/src/components/RealtimeFroala.vue
<template>
  <div>
    <froala :tag="'textarea'" :config="config" v-model="editorContent"></froala>
  </div>
</template>

<script>
export default {
  name: "RealtimeFroala",
  props: {
    apiKey: String,
    docId: String,
    username: String,
    codox: null,
    model: null,
    updateContent: Function,
  },
  watch: {
    docId: function (newVal, oldVal) {
      // reinitialize codox if doc is changed
      if (newVal !== oldVal) {
        this.startCollaboration();
      }
    },
    model: function (newVal, oldVal) {
      if (newVal !== oldVal) {
        this.editorContent = newVal;
      }
    },
  },
  data() {
    const self = this;
    return {
      config: {
        events: {
          initialized: function () {
            // handle froala initialization
            self.froalaInitialized(this);
          },
        },
      },
      editor: null,
      editorContent: this.model,
    };
  },
  beforeDestroy() {
    if (this.codox) {
      //leave the session
      this.codox.stop();
    }
  },
  methods: {
    startCollaboration() {
      // initialization of codox and passing editor object
      setTimeout(() => {
        this.codox.init({
          app: "froala",
          username: this.username,
          docId: this.docId,
          apiKey: this.apiKey,
          editor: this.editor,
          hooks: {
            // invoked whenever the document has been updated
            contentChanged: () => {
              const content = this.editor.html.get();
              this.updateContent(this.docId, content);
            },
          },
        });
      }, 100);
    },
    froalaInitialized(editor) {
      this.editor = editor;
      this.startCollaboration();
    },
  },
};
</script>

<style scoped>
</style>

// froala-angular-codox/src/app/realtime-froala/realtime-froala.component.ts
import { Component, OnInit, OnDestroy, Input, OnChanges, SimpleChanges } from "@angular/core";

declare const Codox: any;

@Component({
  selector: "app-realtime-froala",
  templateUrl: "./realtime-froala.component.html",
  styleUrls: ["./realtime-froala.component.scss"],
})
export class RealtimeFroalaComponent implements OnInit, OnDestroy, OnChanges {
  @Input() apiKey;
  @Input() docId;
  @Input() username;
  @Input() codox;
  @Input() model;
  @Input() boundCallback;

  options: any;
  editor: any;

  constructor() { }

  ngOnInit() {
    const self = this;
    this.options = {
      events: {
        "initialized": function () {
          self.froalaInitialized(this);
        }
      }
    };
  }

  ngOnDestroy() {
    if (this.codox) {
      this.codox.stop();
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    const { docId } = changes;
    if (docId.currentValue !== docId.previousValue) {
      this.startCollaboration();
    }
  }

  startCollaboration() {
    setTimeout(() => {
      this.codox.init({
        app: "froala",
        username: this.username,
        docId: this.docId,
        apiKey: this.apiKey,
        editor: this.editor,
        hooks: {
          // invoked whenever the document has been updated
          contentChanged: () => {
            const content = this.editor.html.get();
            this.boundCallback(this.docId, content);
          },
        },
      });
    }, 100);
  }

  froalaInitialized(editor) {
    this.editor = editor;
    this.startCollaboration();
  }
}
