// quill-angular-codox/src/app/realtime-quill/realtime-quill.component.ts
import { Component, OnInit, OnDestroy, Input, OnChanges, SimpleChanges } from "@angular/core";

declare const Codox: any;

@Component({
  selector: "app-realtime-quill",
  templateUrl: "./realtime-quill.component.html",
  styleUrls: ["./realtime-quill.component.scss"],
})
export class RealtimeQuillComponent implements OnDestroy, OnChanges {
  @Input() apiKey;
  @Input() docId;
  @Input() username;
  @Input() codox;
  @Input() model;
  @Input() boundCallback;

  options: any;
  editor: any;

  constructor() { }


  ngOnDestroy() {
    if (this.codox) {
      this.codox.stop();
    }
  }

  onEditorCreated = (editor) => {
    this.editor = editor;
    this.startCollaboration();
  }

  ngOnChanges(changes: SimpleChanges) {
    const { docId, model } = changes;
    if (docId.currentValue !== docId.previousValue) {
      if (this.editor) {
        const contents = this.editor.clipboard.convert(model.currentValue);
        this.editor.setContents(contents);
      }
      this.startCollaboration();
    }
  }

  startCollaboration() {
    this.editor && this.codox.init({
      app: "quilljs",
      username: this.username,
      docId: this.docId,
      apiKey: this.apiKey,
      editor: this.editor,
      hooks: {
        // invoked whenever the document has been updated
        contentChanged: () => {
          const content = this.editor.root.innerHTML;
          this.boundCallback(this.docId, content);
        },
      },
    });
  }
}

// vue-quill-codox/src/components/RealtimeQuill.vue
<template>
  <div>
    <quill-editor
      v-bind:key="docId"
      ref="myQuillEditor"
      v-model="editorContent"
      style="min-height: 700px"
      @ready="quillInitialized($event)"
    />
  </div>
</template>

<script>
export default {
  name: "RealtimeQuill",
  props: {
    apiKey: String,
    docId: String,
    username: String,
    codox: null,
    model: null,
    updateContent: Function,
  },
  watch: {
    docId: function (newVal, oldVal) {
      // reinitialize codox if doc is changed
      if (newVal !== oldVal) {
        this.startCollaboration();
      }
    },
    model: function (newVal, oldVal) {
      if (newVal !== oldVal) {
        this.editorContent = newVal;
      }
    },
  },
  data() {
    const self = this;
    return {
      editor: null,
      editorContent: self.model,
    };
  },
  beforeDestroy() {
    if (this.codox) {
      this.codox.stop();
    }
  },
  methods: {
    startCollaboration() {
      // initialization of codox and passing editor object
      this.codox &&
        this.codox.init({
          app: "quilljs",
          username: this.username,
          docId: this.docId,
          apiKey: this.apiKey,
          editor: this.editor,
          hooks: {
            // invoked whenever the document has been updated
            contentChanged: () => {
              const content = this.editor.root.innerHTML;
              this.updateContent(this.docId, content);
            },
          },
        });
    },
    quillInitialized(editor) {
      this.editor = editor;
      this.startCollaboration();
    },
  },
};
</script>

<style scoped>
</style>
